name: Build and Push Wechat Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print commit SHA
        run: |
          echo "Full commit SHA: $GITHUB_SHA"
          echo "Short commit SHA: ${GITHUB_SHA::7}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Images
        uses: docker/build-push-action@v6
        with:
          context: ./wechat
          platforms: linux/amd64,linux/arm
          push: true

          tags: |
            weiensong/wechat:${{ github.sha }}
            weiensong/wechat:${{ github.sha::7 }}
            weiensong/wechat:latest
