name: Build and Push Wechat Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print commit SHA
        run: |
          echo "Full commit SHA: $GITHUB_SHA"
          echo "Short commit SHA: ${GITHUB_SHA::7}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker buildx build \
            --platform linux/amd64 \
            --no-cache \
            -t weiensong/wechat_amd64:$SHORT_SHA \
            -t weiensong/wechat_amd64:latest \
            --push \
            ./wechat

      - name: Build and push arm64 image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker buildx build \
            --platform linux/arm64 \
            --no-cache \
            --build-arg TARGETARCH=arm64 \
            -t weiensong/wechat_arm64:$SHORT_SHA \
            -t weiensong/wechat_arm64:latest \
            --push \
            ./wechat
